import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/context/ContextProvider";
import Provider from "@/lib/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gemini",
  description: "Generated by Amar with next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
      <ContextProvider>
      {children}
      </ContextProvider>
      </Provider>
     
</body>
    </html>
  );
}
